version: '1.1'
services:
  backend:
    container_name: node-api
    image: node:16-alpine
    working_dir: /app
    command: npm run container
    user: node:node
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - $PWD:/app
    depends_on:
      - database
  database:
    container_name: mongo-db
    image: mongo:focal
    ports:
      - ${DB_PORT}:${DB_PORT}